version: '3.8'

services:
  # Serviço principal da aplicação
  app:
    image: crypto-data-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - SKIP_DATABASE_CONNECTION=true
    restart: unless-stopped

volumes:
  app_data: 